language: go

addons:
  postgresql: '9.6'

go:
- "1.10"

before_script:
- psql -U postgres -c "CREATE DATABASE clover_test;"

script:
- go test -p=1 -coverprofile=coverage.text -covermode=atomic github.com/nyaruka/rp-clover/...

after_success:
- bash <(curl -s https://codecov.io/bash)
- rm coverage.text
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

