name: CI
on: [push, pull_request]
env:
  go-version: '1.14.x'
jobs:
  test:
    name: Test
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '9.6'
        postgresql db: clover_test
        postgresql user: clover
        postgresql password: clover

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ env.go-version }}

    - name: Run tests
      run: go test -p=1 -coverprofile=coverage.text -covermode=atomic ./...

    - name: Upload coverage
      if: success()
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
  
  release:
    name: Release
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ env.go-version }}

    - name: Publish release
      uses: goreleaser/goreleaser-action@v1
      if: ${{ !contains(github.ref, '-') }}
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish non-master release
      uses: goreleaser/goreleaser-action@v1
      if: contains(github.ref, '-')
      with:
        version: latest
        args: release --rm-dist --skip-validate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
